apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-classifier
  labels:
    app: incident-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incident-classifier
  template:
    metadata:
      labels:
        app: incident-classifier
    spec:
      containers:
      - name: incident-classifier
        image: acrmltesting.azurecr.io/incident-classifier:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: incident-classifier-service
spec:
  selector:
    app: incident-classifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer